name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '0 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  automation:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          mhz2: ${{ secrets.mhz2 }}
        run: |
          printf '%s' "$mhz2" | jq -r .zfc729 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: 7aJk9maE
          path: "*.zip"
          retention-days: 1
